CONTIKI=../../..

DEFINES=PROJECT_CONF_H=\"bridge-conf.h\"
UIP_CONF_IPV6=1


PROJECTDIRS = dev
PROJECT_SOURCEFILES = fakeuip.c sicslow_ethernet.c slip.c

all:	uip6-bridge-tap

include $(CONTIKI)/Makefile.include
